on:
  push:
    branches:
      - main
      - release-**
  pull_request:
  schedule:
  - cron:  '7 7 * * *'

name: build-and-test

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c8454efe5d0bdefd25384362fe217428ca277d57 # v2.2.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Setup rust
        uses: ./.github/actions/setup-rust

      - uses: taiki-e/install-action@ddfbd2cab72fd94842c80ade93f28fe7ee9c71f8 # nextest

      - name: Run cargo test
        shell: bash
        run: cargo nextest run --workspace
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c8454efe5d0bdefd25384362fe217428ca277d57 # v2.2.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Setup rust
        uses: ./.github/actions/setup-rust

      - name: Run cargo build
        shell: bash
        run: cargo build --workspace

      - name: Run cargo clippy
        shell: bash
        run: cargo clippy --workspace

      - name: Run format check
        shell: bash
        run: cargo fmt --check
